### ISSUE TITLE
fit_rdataset.jl does not run

### ISSUE THREAD

**Issue by wlattner** [madeleineudell/LowRankModels.jl#57] opened 2016-05-28 21:49 UTC
I get the following error when running the example in `examples/fit_rdataset.jl`:

```julia
julia> auto_glrm = GLRM(df, 3) ;
WARNING: [a,b,...] concatenation is deprecated; use [a;b;...] instead
 in depwarn at deprecated.jl:73
 in oldstyle_vcat_warning at ./abstractarray.jl:29
 in GLRM at /root/.julia/v0.4/LowRankModels/src/fit_dataframe.jl:22
while loading no file, in expression starting on line 0
WARNING: [a,b,...] concatenation is deprecated; use [a;b;...] instead
 in depwarn at deprecated.jl:73
 in oldstyle_vcat_warning at ./abstractarray.jl:29
 in GLRM at /root/.julia/v0.4/LowRankModels/src/fit_dataframe.jl:23
while loading no file, in expression starting on line 0
ERROR: MethodError: `getindex` has no method matching getindex(::Tuple{DataType,DataType})
Closest candidates are:
  getindex(::Tuple, ::Int64)
  getindex(::Tuple, ::Real)
  getindex(::Tuple, ::AbstractArray{Bool,N})
  ...
 in df_observations at /root/.julia/v0.4/LowRankModels/src/fit_dataframe.jl:41
 in GLRM at /root/.julia/v0.4/LowRankModels/src/fit_dataframe.jl:29
```

The example works just fine if I use an earlier version of LowRankModels.jl (specifically, 676dfc0e7771ba1c2310ec394c3bbbf2ac3d8ab6). Removing `include("scikitlearn.jl")` from `src/LowRankModels.jl` fixes things, but I'm afraid I don't know enough of the Julia language to know why or offer a fix.

**Comment by madeleineudell** [comment] 2016-06-22 03:57
Bill, I'm not able to reproduce this problem, but the line numbers above indicate to me that you have an old version of LowRankModels. Can you checkout master and try again?

**Comment by madeleineudell** [comment] 2016-09-10 17:29
I'm going to close this issue; feel free to reopen if you're still having trouble.

**Closed by madeleineudell** 2016-09-10 17:29 UTC
